version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: bs-platform
    versions:
    - 8.4.2
    - 9.0.0
    - 9.0.1
  - dependency-name: lodash
    versions:
    - 4.17.20
